version 0.3 - fix bug in SSL support - add strict revision/branch checking - add debug option
git-svn-id: http://svn.momonga-linux.org/svn/pkgs/trunk/tools@23505 04999e60-30d4-0310-a325-f3709f8735f4

diff --git a/report-list b/report-list
--- a/report-list
+++ b/report-list
@@ -17,15 +17,21 @@ usage:
 $0  [opts]
     -a    list all status
     -e    list error status only
+    -d    debug mode
     -h    display this help and exit
 EOF
     exit 1
 }
 
-
+conf=report.config
 log=report.log
-opts="-R "
-while getopts "aeh" opt; do
+
+[ -f $conf -a -r $conf ] || error "no report.config"
+source $conf || error "failed to load $conf"
+[ -n "$BRANCH" ] || error "bad config (no BRANCH)"
+
+opts="-R -B $BRANCH"
+while getopts "aehd" opt; do
     case $opt in
 	h) 
 	    usage
@@ -36,6 +42,9 @@ while getopts "aeh" opt; do
 	e) 
 	    opts="$opts -s" 
 	    ;;
+	d)
+	    opts="$opts -d"
+	    ;;
     esac
 done
 shift $(($OPTIND -1))
@@ -43,6 +52,6 @@ shift $(($OPTIND -1))
 FETCH=`dirname $0`/report/list-status.sh
 [ -x $FETCH ] || error "no list-status.sh"
 
-$FETCH $opts $log | awk -F, '{printf("%-40s%s\n",$1,$2)}'
+$FETCH $opts $log | awk -F, '{printf("%-60s%s\n",$1,$2)}'
 
 exit $?
diff --git a/report-upload b/report-upload
--- a/report-upload
+++ b/report-upload
@@ -10,7 +10,31 @@ function error ()
 	exit 1
 }
 
+function usage ()
+{
+    cat<<EOF
+usage:
+$0  [opts]
+    -d    debug mode
+    -h    display this help and exit
+EOF
+    exit 1
+}
+
 export LANG=C
+
+opts=""
+while getopts "dh" opt; do
+    case $opt in
+	h) 
+	    usage
+	    ;;
+	d)
+	    opts="$opts -d"
+	    ;;
+    esac
+done
+shift $(($OPTIND -1))
 
 [ -f report.config ] || error "bad config (no report.config)"
 
@@ -18,7 +42,7 @@ source report.config || error "bad config (source report.config failed)"
 
 [ -n "$REPORT_LOG" ] || error "bad config (no REPORT_LOG)"
 [ -n "$REPORT_URL" ] || error "bad config (no REPORT_URL)"
-
+[ -n "$BRANCH" ] || error "bad config (no BRANCH)"
 
 FETCH=`dirname $0`/report/list-status.sh
 [ -x $FETCH ] || error "no list-status.sh"
@@ -32,11 +56,11 @@ TMP=`mktemp /tmp/report-upload.XXXXXXXX ` || error " mktemp failed."
 TIMESTAMP=`\date +%s`
 
 echo "reading OmoiKondara's logs" > /dev/stderr
-$FETCH -v $REPORT_LOG > $TMP || error "fetch log failed."
+$FETCH $opts -B $BRANCH -v $REPORT_LOG > $TMP || error "fetch log failed."
 
 echo "" > /dev/stderr
 echo "uploading datas to server" > /dev/stderr
-$UPLOAD report.config $TMP || error "upload failed (LOG: $TMP)"
+$UPLOAD $opts report.config $TMP || error "upload failed (LOG: $TMP)"
 
 rm $TMP
 echo $TIMESTAMP >> $REPORT_LOG
